monzo/response

.gitattributes
Add .gitattributes so that shell scripts get the correct line endings when cloning on Windows.
This fixes the below error that was received:
```
response    | /app/startup.sh: line 2: $'\r': command not found
response    | /app/startup.sh: line 3: syntax error near unexpected token `$'\r''
'esponse    | /app/startup.sh: line 3: `wait_for_db()
```
=> Fix line endings on Windows

ui/templates/incident_doc.html, ui/views.py
As a user, I may review an incident channel and decide that I want messages farther back in the channel to be added to the incident timeline. Currently, the messages in the timeline are ordered by the time that they were pinned. I think it would be nice if they were ordered by the actual message timestamp instead of the pinned timestamp, otherwise it could lead to a misleading timeline.
Before
After
=> Updated timeline events to sort by timestamp.

slack/incident_notifications.py
Add a reminder to close the incident after 12 hours of having a comms channel open. This will help with incidents accidentally being left open.
=> Add reminder to close the incident after 12 hours

core/models/incident.py, docker-compose.yaml, slack/models/headline_post.py
Add a status field to the incident headline post so that from a glance the status of the incident can be viewed without depending on the existence of the close button. 🔥 is shown for a live incident and 💧 is shown for an resolved incident.
I played around with the emoji's a little and settled on 🔥 and 💧 but open to suggestions on other combinations that could work.
Also added a dependency on response container for ngrok.
=> Add status to Slack headline incident post

slack/block_kit.py, slack/models/headline_post.py
Without this, block kit messages show `Content cannot be displayed` in notifications
=> Show nicer text in Slack notifications

slack/decorators/incident_notification.py
Prior to this change, a single notification handler failing would take out all notifications.
We expect exceptions to handled by the downstream function, and swallow them if they reach the main notification loop.
=> Guard against notification handlers throwing exceptions

slack/action_handlers.py, slack/views.py
A [previous commit](https://github.com/monzo/response/commit/f840dfa1be89cc3f9d633e25800a89597c7738fc#diff-340b0d779d4d6c958691086a09615c15R85) reversed the label and value of severities used by dialogs.  This caused issues with the app, as we tried to access a dictionary with a string key rather than the expected integer.
=> Fix severity text in dialog

docker-compose.yaml, slack/workflows/pagerduty.py
- Avoid docker-compose volume mount from overwriting the pypd installation in the response container.
- Avoid overflowing the max dialog title length of 20 chars by fixing the string length.
=> Pagerduty Fixes

README.md
Many OSS projects use these shields (from https://shields.io/) to show various bits of status, metadata, etc. - these are the ones I've found which apply to the project. We possibly don't need all of them, but I thought I'd add them to see how they look
=> Add shields to the README

.travis.yml
It looks like having multiple stages under jobs.include means a separate
`deploy` config gets completely ignored. This moves the deploy stage as
just another stage in the jobs matrix.
I've also removed the on.branches config in deploy, as apparently this
is unnecessary when specifying tags:true.
=> Fix travis release mechanism

README.md, response/errors.py, response/slack/decorators/event_handler.py, response/slack/decorators/incident_command.py, response/slack/models/headline_post.py, response/slack/views.py
Adding changes I've made whilst debugging why response wouldn't emoji
react to incident commands. I've added lots of logging - if it's too
noisy, I'm happy to tweak it in future PRs.
The culprit turned out to just be a missing Slack OAuth scope for emoji
reactions
=> Add better logging around Slack events + fix oauth scope

MANIFEST.in
We moved the UI templates from response/ui to response - however the
package manifest was still looking for files to include from
response/ui/templates, so didn't actually package the templates.
=> Include newly moved templates

ui/templates/incident_doc.html
These are sometimes used to inform third parties/regulators and they are in UTC. It's important that recipients are able to determine local time of events and that we don't inadvertently misinform them.
=> Adds timezone to dates on event list

docs/development.md, response/slack/decorators/__init__.py, response/slack/decorators/action_handler.py, response/slack/decorators/event_handler.py, response/slack/decorators/headline_post_action.py, response/slack/decorators/incident_command.py, response/slack/decorators/incident_notification.py, response/slack/decorators/keyword_handler.py, response/slack/models/headline_post.py
Adds a decorator that allows easily populating actions in headline
posts, so that we can add custom integrations there (e.g. PagerDuty).
Also adds a post_to_thread method in HeadlinePost
=>  Populate headline post actions with @headline_post_action 

response/core/models/incident.py, response/core/serializers.py, response/slack/models/comms_channel.py, tests/api/test_incidents.py, tests/factories/incident.py
Uses `RelatedFactory` to create a comms channel in tests.
=> Add comms channel to incident API response

response/core/models/incident.py, response/core/serializers.py, response/core/urls.py, response/core/views.py, tests/api/test_actions.py, tests/api/test_incidents.py, tests/factories/action.py, tests/factories/incident.py
Adds API endpoints for working with incident actions, with the base path `/api/incidents/<incident pk>/actions`:
* `GET` lists actions for a particular incident
* `GET /<pk>` gets a single action
* `POST` creates a new action for that incident
* `PUT /<pk>` updates an action
* `DELETE /<pk>` deletes an action
Currently the DELETE is a "hard delete", i.e. the item actually gets removed from the DB. It wouldn't be too difficult to change this to a "soft delete", i.e. an admin could go back and recover an action, but I didn't think we'd need this right now 👍
=> Add /api/incidents/<incident pk>/actions endpoint

response/core/urls.py, response/core/views.py, tests/api/test_incidents.py, tests/factories/incident.py
Adds an API view that allows listing all incidents in a given calendar
month.
=> Add /incidents/bymonth/2019/08 endpoint

response/slack/decorators/incident_notification.py, response/slack/incident_notifications.py
When an incident is opened, the lead (or reporter if one is not assigned)
will be reminded to close the incident after 24 hours, up to 5 times.
Weekends are filtered out.
It's a bit tricky to test this without refactoring dependencies/side effects
from the notification functions, but it's a small enough change that we
probably don't need to.
=> Periodically remind incident lead to close incident

response/core/serializers.py, tests/api/test_incidents.py
This is a little redundant (since currently `is_closed = end_time == null`), but it gives us the ability to change this definition in future
=> Add "is_closed" field to /api/incidents

response/core/serializers.py, response/slack/client.py, response/slack/models/comms_channel.py, tests/conftest.py
This queries the Slack API for the channel name of a particular ID. This
seems to return pretty quickly, as long as the API response isn't too
long - we can optimise and add caching later on if this becomes a
problem
=> Include Slack channel name in /api/incidents response

response/slack/incident_commands.py, response/slack/signals.py, tests/conftest.py
Uses a pre_save signal to determine if the incident has been closed by this operation (otherwise, if an incident is edited after close, this will fire again).
=> Nudge incident lead to complete a report on close

response/slack/decorators/incident_command.py, response/slack/incident_commands.py
As we can't be sure the decorators will be loaded in a specific order this allows us to ensure we load the default ones and then the custom ones so that we can run a custom overload if it's been provided.
=> Load built in incident commands before the custom ones

response/core/serializers.py, tests/api/test_actions.py, tests/api/test_timeline.py
So that frontends consuming this endpoint can know which ID to update! 
Also, change the `pk` field to `id` so it's a bit nicer in the API.
=> Expose timeline event ID in TimelineEvent endpoint

tests/factories/user.py
This prevents cases where test can fail due to duplicated data, which has been hit in local development
=> Use incrementing IDs for unique fields in factories

README.md, demo/demo/settings/base.py, response/apps.py, response/decorators.py, response/ui/views.py, tests/api/test_incidents.py
This PR introduces on-by-default authentication for the views owned by `response`, plus updates the documentation to recommend a Django Rest Framework setup that is authenticated.
=> Improve Auth

response/core/models/timeline.py, response/slack/signals.py, tests/timeline/test_timeline_events.py
This populates the timeline when key fields in an incident are updated,
e.g. "Incident lead was changed from Barry to Mary".
=> Add timeline events on incident updates

response/core/serializers.py, tests/api/test_timeline.py, tests/factories/timeline.py, tests/timeline/test_timeline_events.py
This fixes another regression. When we changed the JSONField, the
serialization type turned to JSON rendered as a string instead of a
dict. This forces the serializer to return native JSON.
I've also updated the TimelineFactory to generate more types of events - this had the effect of breaking some of the incident update tests (as they only expected a single timeline event of `incident_update` event type to be present), so I've fixed those to retrieve the latest event.
=> api: return timeline event metadata as a dict type, not string

response/slack/signals.py
Currently when you set severity using `@incident severity` it stores an event with metadata of type `incident_impact` (presumably a copy and paste error). this changes the event metadata update type to `incident_severity`.
=> Send correct metadata for update type when setting severity in Slack

response/slack/client.py, tests/slack/test_client.py
Implements a simple retry+incremental backoff for when we get rate limited
by Slack (though easy to enable retries for other errors too).
Given a base backoff (default 200ms) and maximum retries, we retry up to
the max, backing off by the base multiplied by the number of retries. We
could probably use a library to implement a more complex exponential
backoff, but I think this should suffice for now.
I've gone for an iterative approach over recursion to avoid stack
overflows.
=> Handle Slack API rate limiting

docs/slack_app_config.md, response/migrations/0009_commschannel_channel_name.py, response/slack/decorators/event_handler.py, response/slack/event_handlers.py, response/slack/models/comms_channel.py, tests/slack/test_channel_rename.py
Currently any time that `CommsChannel.channel_name` is requested, we go and fetch it from the Slack API. This leads to rate limiting issues when listing a large number of incidents, as Response will call the Slack API for every single incident.
This change caches the channel name in a new model field, updating it whenever we get a `channel_rename` event from Slack. One complication is that we'd like to backfill this for existing CommsChannels in the database (and make the field non-nullable) - I've written a reasonably complex migration that fetches CommsChannel names and populates the field. This has the unfortunate side-effect of requiring a valid `SLACK_TOKEN` environment variable when running migrations.
TODO:
=> Cache CommsChannel channel name

response/core/serializers.py, tests/api/test_timeline.py
The API currently errors with HTTP 400 if we try to create a timeline
event without a metadata tag. This makes the field non-required in the
serializer.
=> timeline api: make metadata optional

response/slack/signals.py
This appears to have been an error during formatting.
=> Fix to make description text instead of tuple

response/core/serializers.py, response/slack/dialog_handlers.py, tests/api/test_incidents.py, tests/test.py
Once a severity has been set it should not be unset, only ever up or downgraded.
=> Ensure the severity field is not unset

response/core/models/__init__.py, response/core/models/action.py, response/core/models/incident.py, response/core/models/timeline.py, response/core/util.py, response/slack/signals.py, setup.py, tests/api/test_actions.py, tests/api/test_incidents.py, tests/api/test_timeline.py
Currently the API (and Slack app) allows users to enter any text they like for various fields - this has security implications if we end up rendering that text in a UI page down the line. Django UI templating handles this case automatically, but other types of UI consuming the API won't - here we sanitize input (using https://pypi.org/project/bleach/) before it gets saved to the DB.
=> core models: sanitize user input

response/core/util.py, tests/core/util_test.py
Bleach doesn't seem to handle None by itself, so we shouldn't pass them to it.
=> Handle None types sent as strings for sanitising with bleach

response/slack/client.py, response/slack/models/comms_channel.py
This is mostly for use in development.  My instance tried to create comms channel #inc-101, but that channel existed already and had been archived, which the app didn't handle.
=> Automatically unarchive channels that have been used before

response/slack/views.py
So that the question of it being a Live incident is first.  As it's a required question, this is a small UX improvement.
=> Reorder the items in the Report Incident Dialog

response/slack/decorators/headline_post_action.py, response/slack/incident_commands.py, response/slack/models/comms_channel.py
We use the name in the DB rather than making a slow call to the Slack API.
Without this change renamed channels still have their original name stored.
=> Store channel name on rename

response/core/serializers.py, response/slack/client.py, response/slack/dialog_handlers.py, response/slack/incident_commands.py, response/slack/models/headline_post.py, response/slack/reference_utils.py, response/templatetags/unslackify.py
Adds an additional field to actions and timeline events so that slack IDs can be represented in human-readable form. These fields are read-only as updates should be applied to the non-mapped field.
Note: With the ability to turn off input sanitization in #171 it's possible to store `<` and `>` in the fields for these models verbatim. The regex that replaces slack IDs will currently only work in this case.
Where there is existing escaped data, we could either modify the regex to match escaped entities like `&lt;` or write a data migration to un-escape existing values. I've decided both of those are outside the scope of this PR ;)
=> Map slack IDs to user/channel in API serializers

response/slack/client.py
Names can be duplicates, have spaces, etc and so using the unique handle for a lookup is far more reliable
=> Look up User Groups by handle and not the name

response/slack/incident_notifications.py
The reminder to close an incident will happen exactly 24 hours after the incident was created which could be at a very unsociable hour. This change will ensure the reminder to close an incident only happens between 9am and 6pm.
=> Limit the closing incident notification to working hours

response/slack/models/comms_channel.py
In `strftime`, %e has a leading space for single digit days.  For example the 5th of the month would print as ' 5' (note the space).
Prior to this change, we were including this space in the call to channels.create, and slack was replacing the space with an extra hyphen.
This meant an incident on November 5th would show as #inc-nov--5-20-51-01 rather than the desired name of #inc-nov-5-20-51-01.
Adding a '-' in the `%e` format trims leading whitespace which corrects the problem.
=> Remove leading space from day in channel creation

response/core/models/incident.py
I missed this in the initial review - it saves having to update
all projects which create incidents outside the response app.
False is a sensible default.
=> Make private a keyword arg

response/core/serializers.py, tests/api/test_events.py, tests/factories/event.py
The payload starts life as an Incident or Event object,
rendered to a JSON string, then stored as a text field.
To enable the JSON renderer in Django Rest Framework to
render this as an object rather than a JSON-encoded string
the easiest option is to deserialize the field prior to
sending it to the renderer.
An alternative would be to override the from_db method on
the Event model, but since we don't need to modify the payload
anywhere, it's simpler to do this in the serializer.
=> Deserialize event payload for API rendering

response/core/views.py, tests/api/test_events.py
Default is the last day if no `from` and `to` params are provided.
=> Enable filtering events by timestamp

response/core/signals.py, tests/api/test_events.py
Tests could do with a bit of de-duplication, but it'd be good to do this
across all API tests.
=> Omit events for private incidents

response/core/serializers.py, response/slack/action_handlers.py, response/slack/dialog_handlers.py, response/slack/models/headline_post.py, response/slack/views.py, response/ui/views.py, tests/api/test_incidents.py, tests/test.py
It feels a little too 'MVP' right now, so we're undoing until it's a more fully formed feature.
=> Removed private incident logic

response/slack/cache.py
Mixing return None with exceptions makes it harder to handle the different failure cases.
This makes it easier as callers can simply handle the SlackError exception.
=> Consistent handling of cache access

response/slack/incident_commands/__init__.py, response/slack/incident_commands/impact.py, response/slack/incident_commands/incident_commands.py, response/slack/incident_commands/summary.py
Prior to this change, the summary and impact commands would overwrite whatever was currently
set for the incident. In most cases, our understanding of these develops over time, so we'd
like to be update and refine what we've previously set.
This change introduces actions and dialogs to update the summary and impact from what was previously
set, making it easier for us to develop meaningful and thorough statements over time.
=> Better summary and impact updates

response/slack/block_kit.py, response/slack/decorators/action_handler.py
Also adds action handler for this type of action
=> Add static select to block kit library

README.md, response/slack/client.py
Slack have re-worked their bot user permission model, and broken the documentation here (and in many other apps -.-)
https://api.slack.com/authentication/token-types#granular_bot
This was the only code usage that prevented me trying out the app, I had to add a lot more permissions than was previously documented as well
https://api.slack.com/methods/chat.postMessage#arg_as_user
cc @ChrisAnn 👋
=> Updates for new slack bot user permissions

response/slack/incident_commands/incident_commands.py
Why have a cheap imitation when you can have the real thing?
=> ⟶: replace ASCII arrow with unicode arrow

demo/demo/settings/dev.py
When running a dev setup I had to change those in my local setup, and given this was a copy of the demo app - this might be interesting for other's as well? :-) 
This should keep previous behaviour the same, but allow overriding the dev DB access defaults via env variables.
=> allow overriding DB access defaults with env variables

response/slack/decorators/event_handler.py
The behaviour here has changed after we've switched to using bot tokens.  We now check whether a message has an attached bot_id to determine whether it's come from a humna or a bot.
=> Exclude bot messages from being handled by the bot

response/templates/home.html
In our installation, the URLs are setup in a way that the UI part has its URLs starting with `/ui/`. When deploying the latest version, we got broken links from the new home page because it has hardcoded path, instead of using the `url` template tag to reverse by name.
=> Fix broken link from incident list when UI isn't at the root

response/slack/incident_notifications.py
Before we had slightly inconsistent phrasing:
- "This incident hasn't got a lead"
- "This incident doesn't have a severity"
Now they are consistent.
- "This incident doesn't have a lead"
- "This incident doesn't have a severity"
=> Consistent reminder wording (hasn't/doesn't)

response/slack/action_handlers.py, response/slack/client.py, response/slack/models/comms_channel.py
Fixes #218 
Pay particular attention to `conversations.join` -- the API is subtly different; Channel ID is required and not channel name.
Edit: there was also a change around `conversations.invite`. I updated this (send a list of users vs. single user), however you do get an error:
```
ERROR - action_handlers - Error calling Slack API endpoint 'conversations.invite': cant_invite_self
```
It seems this inviting of the bot user is unnecessary, as the bot joins the channel anyway during creation.
=> Remove deprecated Slack channel API calls. Use conversations API.
